### ISSUE TITLE
Steps to get it working

### ISSUE THREAD

**Issue by henrik1g** [Jarthianur/VFR-Backend#2]
From what I gathered so far the steps to get the FLARM Radar working would be:

Please correct me if wrong !
- Working rtl-sdr installation
- Install and run ogn-rf and ogn-decode
- Run local aprsc-server
- Make ogn-decode report to localhost instead of glidern{1;2}.glidernet.org
  (How do you accomplish that? DNS spoofing?)
- Build and run VFR-B. Connect VFRB to local aprsc-server
- Connect XCSoar to VFR-B

Some more questions:
Will the new ogn binaries run without connection to the internet? 
What about OGN-DDB whitelist ? Will ogn-decode report targets that are not listed in the DDB?

I hope I can get your system to run here. That would be neat. :-)

**Comment by Jarthianur** [comment]
Hi henrik1g,

I think you can find all the installation steps [here](https://github.com/rueckwaertsflieger/AMVR/wiki).

I will add an installation guide to the wiki though.

"Will the new ogn binaries run without connection to the internet?" -> Our project is made to run almost completely on a local network (except for time-sync, etc.), unless you want that, nothing is going to be sent to the internet.

"What about OGN-DDB whitelist ?" -> I have to admit, I never thought about that, because the aim is to track down ALL aerial vehicles, which send reports via FLARM, or transponder, within configured range and height.

I'm really excited that someone else, than my own club, is interested in that project. ;-)

**Comment by henrik1g** [comment]
Hey thanks for the quick reply,
at this point the wiki is not clear if VFRB can interface directly to the ogn-decode binary or if the intermediate aprsc-server is necessary (which I think it is).
If so, you have to point the ogn-binary somehow to the local aprsc server instead of the internet. How do you guys do this?
Concerning the whitelist part: Me for my part I want to see as much traffic as possible. Just as you.
I just read that there has recently be a large change in ogn following privacy law concerns. And (as i understand it) therefore using a whitelist of people who signed up on their site.
I was now wondering if this filtering is already done in the ogn-decode binary and if so can be switched off so that all traffic is seen.

**Comment by henrik1g** [comment]
I think I found the answers here:
http://wiki.glidernet.org/wiki:receiver-config-file

**Comment by Jarthianur** [comment]
Hello,

yes an aprsc-server is definitely necessary.
See the wiki for how to configure aprsc to run local.

The thing is, VFR-B is actually a subsystem to the AMVR, even this subsystem is in a ready-to-be-used state, the AMVR isn't. We are still in deep development and there will be a lot of time gone until we will release the whole Project with detailed step-by-step guide.

Although I will update my wiki more and more to make it easier to set up all components.

**Comment by Jarthianur** [comment]
Also I have to correct myself,
for time-sync there is an internet connection needed.

**Comment by Jarthianur** [comment]
About the OGN whitelist,

as far as I understood operations of the latest OGN receiver binaries, yes. However, the entire OGN system will never broadcast blacklisted (not white-listed) devices to any internet client.  The receiver itself (operating locally) was enabled to blacklist-filter Flarms only, if you would provide the DB locally in an up to date version.
It is not enabled to use a local DB. Thus, the Flarm targets will be reported but in a raw format only.
To fully understand the blacklist conf / not-track options, please get more information on the OGN wiki and user forum.
To enrich the data from the receiver you have to involve the flarmnet DB that is allowed for local enrichment of the received data. That turns out to be the very same operation as using a classic Flarm plus XCSoar using the flamnet DB.
